name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: submodules
      run: git submodule update --init --recursive
    - name: build
      run: ./build.sh
    - name: test
      run: build/test/Test
    - name: getpytest
      run: pip install pytest
    - name: endtoend
      run: py.test test/EndToEnd/EndToEndTest.py
