name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: submodules
      run: git submodule update --init --recursive
    - name: build
      run: ./build.sh debug
    - name: test
      run: build/test/Test
    - name: getpytest
      run: python -m pip install pytest requests
    - name: runpotato
      run: build/potato &
    - name: endtoend
      run: python -m pytest test/EndToEnd/EndToEndTest.py
